name: Main workflow
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check-out repo
        uses: actions/checkout@v2
      - name: Setup PHP 8.1
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
      - name: Run composer installer
        run: make install
      - name: Run phpcs linter
        run: make lint
      - name: Run phpunit tests
        run: make test
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageLocations: ${{github.workspace}}/clover.xml:clover
          debug: true
